# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path

def relative_to_bg(path: str) -> Path:
        return BG_PATH / Path(path)
OUTPUT_PATH = Path(__file__).parent
BG_PATH = OUTPUT_PATH / Path("./backgrounds")

class Ui_CalcWindow(object):
    def setupUi(self, CalcWindow):
        CalcWindow.setObjectName("CalcWindow")
        CalcWindow.resize(500, 529)
        self.centralwidget = QtWidgets.QWidget(CalcWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(0, 0, 500, 511))
        self.Tabs.setObjectName("Tabs")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.About = QtWidgets.QLabel(self.tab_1)
        self.About.setGeometry(QtCore.QRect(0, 0, 500, 489))
        self.About.setText("")
        self.About.setPixmap(QtGui.QPixmap(str(relative_to_bg("About.jpg"))))
        self.About.setObjectName("About")
        self.Tabs.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Instructions = QtWidgets.QLabel(self.tab_2)
        self.Instructions.setGeometry(QtCore.QRect(0, 0, 500, 489))
        self.Instructions.setText("")
        self.Instructions.setPixmap(QtGui.QPixmap(str(relative_to_bg("Instructions.jpg"))))
        self.Instructions.setObjectName("Instructions")
        self.Tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.View_Presets = QtWidgets.QLabel(self.tab_3)
        self.View_Presets.setGeometry(QtCore.QRect(0, 0, 500, 487))
        self.View_Presets.setText("")
        self.View_Presets.setPixmap(QtGui.QPixmap(str(relative_to_bg("View Presets.jpg"))))
        self.View_Presets.setObjectName("View_Presets")
        self.Display = QtWidgets.QLabel(self.tab_3)
        self.Display.setGeometry(QtCore.QRect(35, 130, 430, 315))
        self.Display.setStyleSheet("background-color: (212, 252, 255, 1);\n"
"font: italic 16pt \"Comic Sans MS\";")
        self.Display.setText("")
        self.Display.setObjectName("Display")
        self.Tabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Edit_Presets = QtWidgets.QLabel(self.tab_4)
        self.Edit_Presets.setGeometry(QtCore.QRect(0, 0, 500, 489))
        self.Edit_Presets.setText("")
        self.Edit_Presets.setPixmap(QtGui.QPixmap(str(relative_to_bg("Edit Presets.jpg"))))
        self.Edit_Presets.setObjectName("Edit_Presets")
        self.Input_1 = QtWidgets.QLineEdit(self.tab_4)
        self.Input_1.setGeometry(QtCore.QRect(36, 189, 191, 31))
        self.Input_1.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"font: 75 11pt \"Comic Sans MS\";\n"
"")
        self.Input_1.setFrame(False)
        self.Input_1.setObjectName("Input_1")
        self.Input_2 = QtWidgets.QLineEdit(self.tab_4)
        self.Input_2.setGeometry(QtCore.QRect(250, 189, 221, 31))
        self.Input_2.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"font: 75 11pt \"Comic Sans MS\";\n"
"")
        self.Input_2.setFrame(False)
        self.Input_2.setObjectName("Input_2")
        self.Input_3 = QtWidgets.QLineEdit(self.tab_4)
        self.Input_3.setGeometry(QtCore.QRect(36, 255, 191, 31))
        self.Input_3.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"font: 75 11pt \"Comic Sans MS\";\n"
"")
        self.Input_3.setFrame(False)
        self.Input_3.setObjectName("Input_3")
        self.Input_4 = QtWidgets.QLineEdit(self.tab_4)
        self.Input_4.setGeometry(QtCore.QRect(250, 255, 221, 31))
        self.Input_4.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"font: 75 11pt \"Comic Sans MS\";\n"
"")
        self.Input_4.setFrame(False)
        self.Input_4.setObjectName("Input_4")
        self.Input_5 = QtWidgets.QLineEdit(self.tab_4)
        self.Input_5.setGeometry(QtCore.QRect(36, 374, 191, 31))
        self.Input_5.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"font: 75 11pt \"Comic Sans MS\";\n"
"")
        self.Input_5.setFrame(False)
        self.Input_5.setObjectName("Input_5")
        self.Input_6 = QtWidgets.QLineEdit(self.tab_4)
        self.Input_6.setGeometry(QtCore.QRect(250, 374, 221, 31))
        self.Input_6.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"font: 75 11pt \"Comic Sans MS\";\n"
"")
        self.Input_6.setFrame(False)
        self.Input_6.setObjectName("Input_6")
        self.Sub_But = QtWidgets.QPushButton(self.tab_4)
        self.Sub_But.setGeometry(QtCore.QRect(193, 426, 111, 31))
        self.Sub_But.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"background-color: rgba(170, 163, 255, 1);\n"
"")
        self.Sub_But.setObjectName("Sub_But")
        self.Tabs.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Calculator = QtWidgets.QLabel(self.tab_5)
        self.Calculator.setGeometry(QtCore.QRect(0, 0, 500, 489))
        self.Calculator.setText("")
        self.Calculator.setPixmap(QtGui.QPixmap(str(relative_to_bg("Calculator.jpg"))))
        self.Calculator.setObjectName("Calculator")
        self.Expression = QtWidgets.QPlainTextEdit(self.tab_5)
        self.Expression.setGeometry(QtCore.QRect(35, 170, 431, 71))
        self.Expression.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"font: 75 12pt \"Comic Sans MS\";\n"
"")
        self.Expression.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Expression.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Expression.setLineWidth(7)
        self.Expression.setObjectName("Expression")
        self.Answer = QtWidgets.QLabel(self.tab_5)
        self.Answer.setGeometry(QtCore.QRect(40, 310, 421, 31))
        self.Answer.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"")
        self.Answer.setText("")
        self.Answer.setObjectName("Answer")
        self.Clear_But = QtWidgets.QPushButton(self.tab_5)
        self.Clear_But.setGeometry(QtCore.QRect(197, 393, 111, 31))
        self.Clear_But.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"background-color: rgba(170, 163, 255, 1);\n"
"")
        self.Clear_But.setObjectName("Clear_But")
        self.Eval_But = QtWidgets.QPushButton(self.tab_5)
        self.Eval_But.setGeometry(QtCore.QRect(44, 393, 111, 31))
        self.Eval_But.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"background-color: rgba(170, 163, 255, 1);\n"
"")
        self.Eval_But.setObjectName("Eval_But")
        self.Speak_But = QtWidgets.QPushButton(self.tab_5)
        self.Speak_But.setGeometry(QtCore.QRect(348, 393, 111, 31))
        self.Speak_But.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"background-color: rgba(170, 163, 255, 1);\n"
"")
        self.Speak_But.setObjectName("Speak_But")
        self.Tabs.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.Memory = QtWidgets.QLabel(self.tab_6)
        self.Memory.setGeometry(QtCore.QRect(0, 0, 500, 489))
        self.Memory.setText("")
        self.Memory.setPixmap(QtGui.QPixmap(str(relative_to_bg("Memory.jpg"))))
        self.Memory.setObjectName("Memory")
        self.Mem_Display = QtWidgets.QLabel(self.tab_6)
        self.Mem_Display.setGeometry(QtCore.QRect(40, 130, 421, 251))
        self.Mem_Display.setStyleSheet("background-color: rgba(212, 252, 255, 1);\n"
"font: 75 14pt \"Comic Sans MS\";\n"
"")
        self.Mem_Display.setText("")
        self.Mem_Display.setWordWrap(True)
        self.Mem_Display.setObjectName("Mem_Display")
        self.Del_But = QtWidgets.QPushButton(self.tab_6)
        self.Del_But.setGeometry(QtCore.QRect(173, 405, 171, 31))
        self.Del_But.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"background-color: rgba(170, 163, 255, 1);\n"
"")
        self.Del_But.setObjectName("Del_But")
        self.Tabs.addTab(self.tab_6, "")
        CalcWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CalcWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        CalcWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CalcWindow)
        self.statusbar.setObjectName("statusbar")
        CalcWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CalcWindow)
        self.Tabs.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(CalcWindow)

    def retranslateUi(self, CalcWindow):
        _translate = QtCore.QCoreApplication.translate
        CalcWindow.setWindowTitle(_translate("CalcWindow", "AlphaCalc"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_1), _translate("CalcWindow", "About"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("CalcWindow", "Instructions"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_3), _translate("CalcWindow", "View Presets"))
        self.Sub_But.setText(_translate("CalcWindow", "Submit"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_4), _translate("CalcWindow", "Edit Presets"))
        self.Clear_But.setText(_translate("CalcWindow", "Clear"))
        self.Eval_But.setText(_translate("CalcWindow", "Evaluate"))
        self.Speak_But.setText(_translate("CalcWindow", "Speak"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_5), _translate("CalcWindow", "Calculator"))
        self.Del_But.setText(_translate("CalcWindow", "Clear Memory"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_6), _translate("CalcWindow", "Memory"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalcWindow = QtWidgets.QMainWindow()
    ui = Ui_CalcWindow()
    ui.setupUi(CalcWindow)
    CalcWindow.show()
    sys.exit(app.exec_())
